# Generated by Django 3.2.7 on 2021-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/static/img', verbose_name='Изображение'),
        ),
    ]
