# Generated by Django 3.2.7 on 2021-09-18 20:34

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'verbose_name': 'Акссесуар', 'verbose_name_plural': 'Акссесуары'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='big_image',
            field=models.ImageField(null=True, upload_to='catalog/static/img', validators=[catalog.validators.image_resolution_check_big], verbose_name='Большое Изображение'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/static/img', validators=[catalog.validators.image_resolution_check_small], verbose_name='Маленькое Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
    ]
