# Generated by Django 3.2.7 on 2021-09-21 06:48

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210918_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', validators=[catalog.validators.image_resolution_check_big], verbose_name='Большое Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', validators=[catalog.validators.image_resolution_check_small], verbose_name='Маленькое Изображение'),
        ),
    ]
