# Generated by Django 3.2.7 on 2021-09-27 17:50

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', validators=[catalog.validators.image_resolution_check_cart], verbose_name='Изображение для таблицы'),
        ),
    ]
